Updated and streamlined demo

diff --git a/Dockerfile.openvino b/Dockerfile.openvino
--- a/Dockerfile.openvino
+++ b/Dockerfile.openvino
@@ -1,12 +1,12 @@
 #Based on https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_docker_linux.html
 FROM ubuntu:18.04
-
 USER root
 WORKDIR /
+SHELL ["/bin/bash", "-xo", "pipefail", "-c"]
 
+# Creating user openvino
 RUN useradd -ms /bin/bash openvino && \
     chown openvino -R /home/openvino
-
 ARG DEPENDENCIES="autoconf \
                   automake \
                   build-essential \
@@ -19,25 +19,60 @@ ARG DEPENDENCIES="autoconf \
                   lsb-release \
                   libgtk-3-0 \
                   libtool \
-                  python3-pip \
                   udev \
-                  unzip"
+                  unzip \
+                  dos2unix"
 
 RUN apt-get update && \
     apt-get install -y --no-install-recommends ${DEPENDENCIES} && \
     rm -rf /var/lib/apt/lists/*
 
-ARG DOWNLOAD_LINK=http://registrationcenter-download.intel.com/akdlm/irc_nas/16612/l_openvino_toolkit_p_2020.2.120.tgz
+WORKDIR /thirdparty
+RUN sed -Ei 's/# deb-src /deb-src /' /etc/apt/sources.list && \
+    apt-get update && \
+    apt-get source ${DEPENDENCIES} && \
+    rm -rf /var/lib/apt/lists/*
 
+# setup Python
+ENV PYTHON python3.6
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends python3-pip python3-dev lib${PYTHON} wget && \
+    rm -rf /var/lib/apt/lists/*
+ARG package_url=http://registrationcenter-download.intel.com/akdlm/irc_nas/16612/l_openvino_toolkit_p_2020.2.120.tgz
+ARG TEMP_DIR=/tmp/openvino_installer
+WORKDIR ${TEMP_DIR}
+RUN wget ${package_url} 
+
+# install product by installation script
+ENV INTEL_OPENVINO_DIR /opt/intel/openvino
+RUN tar -xzf ${TEMP_DIR}/*.tgz --strip 1
+RUN sed -i 's/decline/accept/g' silent.cfg && \
+    ${TEMP_DIR}/install.sh -s silent.cfg && \
+    ${INTEL_OPENVINO_DIR}/install_dependencies/install_openvino_dependencies.sh
 WORKDIR /tmp
-ENV INSTALL_DIR /opt/intel/openvino
+RUN rm -rf ${TEMP_DIR}
 
-RUN curl -LOJ "${DOWNLOAD_LINK}" && \
-    tar -xzf ./*.tgz && \
-    cd l_openvino_toolkit* && \
-    sed -i 's/decline/accept/g' silent.cfg && \
-    ./install.sh -s silent.cfg && \
-    rm -rf /tmp/* && \
-    $INSTALL_DIR/install_dependencies/install_openvino_dependencies.sh
+# installing dependencies for package
+WORKDIR /tmp
+RUN ${PYTHON} -m pip install --no-cache-dir setuptools && \
+    find "${INTEL_OPENVINO_DIR}/" -type f -name "*requirements*.*" -path "*/${PYTHON}/*" -exec ${PYTHON} -m pip install --no-cache-dir -r "{}" \; && \
+    find "${INTEL_OPENVINO_DIR}/" -type f -name "*requirements*.*" -not -path "*/post_training_optimization_toolkit/*" -not -name "*windows.txt"  -not -name "*ubuntu16.txt" -not -path "*/python3*/*" -not -path "*/python2*/*" -exec ${PYTHON} -m pip install --no-cache-dir -r "{}" \;
+WORKDIR ${INTEL_OPENVINO_DIR}/deployment_tools/open_model_zoo/tools/accuracy_checker
+RUN source ${INTEL_OPENVINO_DIR}/bin/setupvars.sh && \
+    ${PYTHON} -m pip install --no-cache-dir -r ${INTEL_OPENVINO_DIR}/deployment_tools/open_model_zoo/tools/accuracy_checker/requirements.in && \
+    ${PYTHON} ${INTEL_OPENVINO_DIR}/deployment_tools/open_model_zoo/tools/accuracy_checker/setup.py install
+WORKDIR ${INTEL_OPENVINO_DIR}/deployment_tools/tools/post_training_optimization_toolkit
+RUN if [ -f requirements.txt ]; then \
+        ${PYTHON} -m pip install --no-cache-dir -r ${INTEL_OPENVINO_DIR}/deployment_tools/tools/post_training_optimization_toolkit/requirements.txt && \
+        ${PYTHON} ${INTEL_OPENVINO_DIR}/deployment_tools/tools/post_training_optimization_toolkit/setup.py install; \
+    fi;
 
+# Post-installation cleanup and setting up OpenVINO environment variables
+RUN if [ -f "${INTEL_OPENVINO_DIR}"/bin/setupvars.sh ]; then \
+        printf "\nsource \${INTEL_OPENVINO_DIR}/bin/setupvars.sh\n" >> /home/openvino/.bashrc; \
+        printf "\nsource \${INTEL_OPENVINO_DIR}/bin/setupvars.sh\n" >> /root/.bashrc; \
+    fi;
+RUN find "${INTEL_OPENVINO_DIR}/" -name "*.*sh" -type f -exec dos2unix {} \;
+WORKDIR ${INTEL_OPENVINO_DIR}
+CMD ["/bin/bash"]
 
